name: Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: 1.10.3.933

      - name: Run Tests
        run: clojure -M:test:test/run

      - name: Build Jar
        run: |
          clojure -T:build jar
          ls .build/*.jar

      - name: Deploy Jar
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: clojure -T:build deploy
        env:
          CLOJARS_USERNAME: fbeyer
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
